Implement test for calculate average
UBC-MDS/featurescreator pull request #27
Opened 2022-01-28 08:12 UTC by SonQBChau

2022-01-28 23:10 UTC, NikitaShymberg requested changes
The tests failed for me because (I think) `get_matching_column_names` is not implemented. Could you `git rebase` or `git merge` main into your branch so that the tests pass?

2022-01-28 23:10 UTC, NikitaShymberg commented on R/features_creator.R
> +#' c(4, 5, 6)
Nitpick: Could you delete this?

2022-01-28 23:34 UTC, SonQBChau commented on R/features_creator.R
> +#' c(4, 5, 6)
done

2022-01-28 23:35 UTC, SonQBChau commented
I just merged the main again, there error should go away

2022-01-29 00:11 UTC, NikitaShymberg commented
Thanks Son, I've reviewed this and everything looks good now.

I had to make some small changes to make `check()` pass. I removed the definition of `calculate_average()` from `features_creator.R` (though I thought that the diff said that you did this but that's not what it looked like when I pulled the branch, idk what happened). I had to change some `None`s to `NULL`s from Rakesh's function definitions as well.

Anyway, everything works feel free to merge!

2022-01-29 00:11 UTC, NikitaShymberg approved these changes

2022-01-29 21:25 UTC, merged